/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/student/application': RouteRecordInfo<'/student/application', '/student/application', Record<never, never>, Record<never, never>>,
    '/student/examination': RouteRecordInfo<'/student/examination', '/student/examination', Record<never, never>, Record<never, never>>,
    '/student/practice': RouteRecordInfo<'/student/practice', '/student/practice', Record<never, never>, Record<never, never>>,
    '/student/report': RouteRecordInfo<'/student/report', '/student/report', Record<never, never>, Record<never, never>>,
    '/student/stumain': RouteRecordInfo<'/student/stumain', '/student/stumain', Record<never, never>, Record<never, never>>,
    '/teacher/prcManage': RouteRecordInfo<'/teacher/prcManage', '/teacher/prcManage', Record<never, never>, Record<never, never>>,
    '/teacher/prcPublic': RouteRecordInfo<'/teacher/prcPublic', '/teacher/prcPublic', Record<never, never>, Record<never, never>>,
    '/teacher/stuManage': RouteRecordInfo<'/teacher/stuManage', '/teacher/stuManage', Record<never, never>, Record<never, never>>,
    '/teacher/tealogin': RouteRecordInfo<'/teacher/tealogin', '/teacher/tealogin', Record<never, never>, Record<never, never>>,
    '/teacher/teamain': RouteRecordInfo<'/teacher/teamain', '/teacher/teamain', Record<never, never>, Record<never, never>>,
  }
}
